"""initial

Revision ID: 2707a922a1f4
Revises: 
Create Date: 2023-09-19 12:54:16.355841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2707a922a1f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('register_sign', sa.String(), nullable=False),
    sa.Column('car_year', sa.Integer(), nullable=False),
    sa.CheckConstraint("register_sign ~ '^([0-9]|E|I)[0-9]{3}[ABEIKMHOPCTX]{2}[0-7]$'", name='check_sign_format'),
    sa.CheckConstraint('LENGTH(register_sign) = 7', name='check_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register_sign')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
